services:
  - type: web
    name: game-backend
    env: node
    rootDir: backend
    branch: master
    buildCommand: cd backend; yarn
    startCommand: ts-node backend/index.ts
    staticPublishPath: ./backend
  - type: web
    name: game-frontend
    branch: master
    env: node
    buildCommand: cd frontend; yarn; yarn build
    startCommand: cd frontend; yarn start
    staticPublishPath: ./frontend/build/
